version: '3'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    image: vilmena/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/app/media

  frontend:
    image: vilmena/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static

  gateway:
    image: vilmena/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - foodgram_static:/staticfiles
      - foodgram_media:/app/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 7080:80