# Generated by Django 5.1.1 on 2024-10-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
